import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm'; import { Repository } from 'typeorm';
import { KnownTenantTransactionRunner } from '../../../common/tenant-context/known-tenant-transaction-runner.js'; import { TenantAwareTransactionRunner } from '../../../common/tenant-context/tenant-aware-transaction-runner.js'; import { AUDIT_EVENT_PORT, type AuditEventPort } from '../../../common/audit/audit-event.port.js';
import { FpoRegistrationEntity, FpoRegistrationStatus } from '../../priority1-auth-registration/entities/fpo-registration.entity.js'; import { MemberApplicationEntity, MemberApplicationStatus } from '../entities/member-application.entity.js'; import { LoanApplicationEntity, LoanApplicationStatus } from '../entities/loan-application.entity.js'; import type { CreateLoanApplicationDto, DisburseLoanDto, FieldVisitDto, SanctionLoanDto } from '../dto/loan-application.dto.js';
@Injectable() export class LoanApplicationService {
 constructor(@InjectRepository(FpoRegistrationEntity) private readonly fpos:Repository<FpoRegistrationEntity>, private readonly knownTx:KnownTenantTransactionRunner, private readonly tenantTx:TenantAwareTransactionRunner, @Inject(AUDIT_EVENT_PORT) private readonly audit:AuditEventPort) {}
 async apply(dto:CreateLoanApplicationDto) { const code=dto.fpoCode.toUpperCase(); const fpo=await this.fpos.findOne({where:{fpoCode:code,status:FpoRegistrationStatus.ACTIVE}}); if(!fpo) throw new NotFoundException('Active FPO Code was not found.'); const loan=await this.knownTx.run(fpo.id,async m=>{ const members=m.getRepository(MemberApplicationEntity); const member=await members.findOne({where:{tenantId:fpo.id,applicationNumber:dto.memberApplicationNumber}}); if(!member) throw new NotFoundException('Shareholder application was not found.'); const repo=m.getRepository(LoanApplicationEntity); const serial=String((await repo.count({where:{tenantId:fpo.id}}))+1).padStart(5,'0'); return repo.save(repo.create({tenantId:fpo.id,loanApplicationNumber:`${code}-LOAN-${serial}`,memberApplicationId:member.id,memberApplicationNumber:member.applicationNumber,fullName:member.fullName,mobile:member.mobile,email:member.email,address:member.address,village:member.village,district:member.district,state:member.state,pincode:member.pincode,fatherOrSpouseName:dto.fatherOrSpouseName??null,maritalStatus:dto.maritalStatus??null,religionCaste:dto.religionCaste??null,occupation:dto.occupation??null,businessName:dto.businessName??null,purposeOfLoan:dto.purposeOfLoan,requestedAmount:dto.requestedAmount,requestedTermMonths:dto.requestedTermMonths,bankName:dto.bankName??null,bankAccountNumber:dto.bankAccountNumber??null,ifsc:dto.ifsc??null,existingCreditDetails:dto.existingCreditDetails??null,collateralDetails:dto.collateralDetails??null,guarantorName:dto.guarantorName??null,guarantorMobile:dto.guarantorMobile??null,status:LoanApplicationStatus.SUBMITTED,fieldVisitDate:null,fieldVisitOfficer:null,fieldVisitObservations:null,fieldVisitRecommendation:null,sanctionedAmount:null,sanctionedTermMonths:null,interestRate:null,processingFeeRate:null,repaymentFrequency:null,sanctionDate:null,sanctionLetterIssuedAt:null,agreementExecutedAt:null,disbursedAt:null,disbursementMode:null,disbursementReference:null,decisionNote:null})); }); await this.audit.record({eventType:'loan.application.submitted',tenantId:fpo.id,subjectId:loan.id,metadata:{loanApplicationNumber:loan.loanApplicationNumber}}); return {loanApplicationNumber:loan.loanApplicationNumber,status:loan.status}; }
 list(tenantId:string){return this.tenantTx.run(m=>m.getRepository(LoanApplicationEntity).find({where:{tenantId},order:{createdAt:'DESC'}}));}
 async documents(tenantId:string,id:string){const loan=await this.one(tenantId,id);const fpo=await this.fpos.findOne({where:{id:tenantId}});return {fpoName:fpo?.fpoName??'FPO',fpoCode:fpo?.fpoCode??'',cin:fpo?.cin??'',registeredAddress:fpo?.registeredAddress??'',loan};}
 private async one(tenantId:string,id:string){const row=await this.tenantTx.run(m=>m.getRepository(LoanApplicationEntity).findOne({where:{tenantId,id}}));if(!row)throw new NotFoundException('Loan application not found.');return row;}
 async beginReview(tenantId:string,actor:string,id:string){return this.change(tenantId,actor,id,LoanApplicationStatus.SUBMITTED,LoanApplicationStatus.UNDER_REVIEW,'loan.application.review_started');}
 async fieldVisit(tenantId:string,actor:string,id:string,dto:FieldVisitDto){return this.tenantTx.run(async m=>{const r=m.getRepository(LoanApplicationEntity);const x=await r.findOne({where:{tenantId,id}});if(!x||x.status!==LoanApplicationStatus.UNDER_REVIEW)throw new ConflictException('Field visit is available after review starts.');Object.assign(x,{fieldVisitDate:dto.fieldVisitDate,fieldVisitOfficer:dto.officer,fieldVisitObservations:dto.observations,fieldVisitRecommendation:dto.recommendation,status:LoanApplicationStatus.FIELD_VISIT_COMPLETED});const saved=await r.save(x);await this.audit.record({eventType:'loan.field_visit.completed',tenantId,actorUserId:actor,subjectId:id,metadata:{recommendation:dto.recommendation}});return saved;});}
 async sanction(tenantId:string,actor:string,id:string,dto:SanctionLoanDto){return this.tenantTx.run(async m=>{const loans=m.getRepository(LoanApplicationEntity),members=m.getRepository(MemberApplicationEntity);const x=await loans.findOne({where:{tenantId,id}});if(!x||x.status!==LoanApplicationStatus.FIELD_VISIT_COMPLETED)throw new ConflictException('Sanction is available after field visit.');if(x.fieldVisitRecommendation!=='RECOMMEND')throw new BadRequestException('Field visit has not recommended this loan.');const member=await members.findOne({where:{tenantId,id:x.memberApplicationId}});if(!member||member.status!==MemberApplicationStatus.APPROVED)throw new BadRequestException('Shareholder approval is required before sanction.');Object.assign(x,{sanctionedAmount:dto.sanctionedAmount,sanctionedTermMonths:dto.termMonths,interestRate:dto.interestRate,processingFeeRate:dto.processingFeeRate,repaymentFrequency:dto.repaymentFrequency,sanctionDate:dto.sanctionDate,status:LoanApplicationStatus.SANCTIONED});const saved=await loans.save(x);await this.audit.record({eventType:'loan.sanctioned',tenantId,actorUserId:actor,subjectId:id,metadata:{loanApplicationNumber:saved.loanApplicationNumber}});return saved;});}
 async issueSanctionLetter(tenantId:string,actor:string,id:string){return this.tenantTx.run(async m=>{const r=m.getRepository(LoanApplicationEntity);const x=await r.findOne({where:{tenantId,id}});if(!x||![LoanApplicationStatus.SANCTIONED,LoanApplicationStatus.AGREEMENT_EXECUTED,LoanApplicationStatus.DISBURSED].includes(x.status))throw new ConflictException('Sanction letter is available only after sanction.');if(!x.sanctionLetterIssuedAt){x.sanctionLetterIssuedAt=new Date();await r.save(x);await this.audit.record({eventType:'loan.sanction_letter.issued',tenantId,actorUserId:actor,subjectId:id,metadata:{loanApplicationNumber:x.loanApplicationNumber}});}return x;});}
 async agreement(tenantId:string,actor:string,id:string){return this.tenantTx.run(async m=>{const r=m.getRepository(LoanApplicationEntity);const x=await r.findOne({where:{tenantId,id}});if(!x||x.status!==LoanApplicationStatus.SANCTIONED)throw new ConflictException('Agreement execution is available after sanction.');if(!x.sanctionLetterIssuedAt)throw new BadRequestException('Issue and record the sanction letter before executing the agreement.');x.status=LoanApplicationStatus.AGREEMENT_EXECUTED;x.agreementExecutedAt=new Date();const saved=await r.save(x);await this.audit.record({eventType:'loan.agreement.executed',tenantId,actorUserId:actor,subjectId:id});return saved;});}
 async disburse(tenantId:string,actor:string,id:string,dto:DisburseLoanDto){return this.tenantTx.run(async m=>{const r=m.getRepository(LoanApplicationEntity);const x=await r.findOne({where:{tenantId,id}});if(!x||x.status!==LoanApplicationStatus.AGREEMENT_EXECUTED)throw new ConflictException('Disbursement is available after agreement execution.');Object.assign(x,{status:LoanApplicationStatus.DISBURSED,disbursedAt:new Date(),disbursementMode:dto.mode,disbursementReference:dto.reference});const saved=await r.save(x);await this.audit.record({eventType:'loan.disbursed',tenantId,actorUserId:actor,subjectId:id,metadata:{mode:dto.mode}});return saved;});}
 async reject(tenantId:string,actor:string,id:string,reason:string){const x=await this.one(tenantId,id);if([LoanApplicationStatus.DISBURSED,LoanApplicationStatus.REJECTED].includes(x.status))throw new ConflictException('This loan can no longer be rejected.');return this.tenantTx.run(async m=>{const r=m.getRepository(LoanApplicationEntity);await r.update({id,tenantId},{status:LoanApplicationStatus.REJECTED,decisionNote:reason});await this.audit.record({eventType:'loan.rejected',tenantId,actorUserId:actor,subjectId:id,metadata:{reason}});return r.findOneByOrFail({id,tenantId});});}
 private async change(tenantId:string,actor:string,id:string,from:LoanApplicationStatus,to:LoanApplicationStatus,event:string){return this.tenantTx.run(async m=>{const r=m.getRepository(LoanApplicationEntity);const x=await r.findOne({where:{tenantId,id}});if(!x||x.status!==from)throw new ConflictException('This action is not available at the current stage.');x.status=to;const saved=await r.save(x);await this.audit.record({eventType:event,tenantId,actorUserId:actor,subjectId:id});return saved;});}
}
