import { ForbiddenException, Injectable, Inject, NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type { Redis } from 'ioredis';
import { DataSource } from 'typeorm';
import { randomBytes } from 'node:crypto';
import { REDIS_CLIENT } from '../../../common/session/redis-client.provider.js';
import { EMAIL_DELIVERY_PORT, type EmailDeliveryPort } from '../../../common/delivery/email-delivery.port.js';
import { PasswordHasher } from '../../../common/security/password-hasher.js';
import { SecretTokenHasher } from '../../../common/security/secret-token-hasher.js';
import { PlatformAdminAccountEntity, PlatformAdminRole } from '../entities/platform-admin-account.entity.js';
import { TotpService } from './totp.service.js';
@Injectable()
export class PlatformAdminBootstrapService {
 constructor(private readonly dataSource:DataSource,private readonly config:ConfigService,private readonly hasher:PasswordHasher,private readonly tokenHasher:SecretTokenHasher,private readonly totp:TotpService,@Inject(REDIS_CLIENT) private readonly redis:Redis,@Inject(EMAIL_DELIVERY_PORT) private readonly email:EmailDeliveryPort){}
 async issueFirstAdminSetup(key:string){const expected=this.config.get<string>('PLATFORM_ADMIN_BOOTSTRAP_KEY'),email=this.config.get<string>('INITIAL_PLATFORM_ADMIN_EMAIL'),username=this.config.get<string>('INITIAL_PLATFORM_ADMIN_USERNAME');if(!expected||key!==expected||!email||!username)throw new ForbiddenException('Initial Platform Admin setup is not available.');const repo=this.dataSource.getRepository(PlatformAdminAccountEntity);let admin=await repo.findOne({where:[{username},{email}]});if(admin?.totpEnabled){admin.totpEnabled=false;admin.totpSecret=null;await repo.save(admin);}if(!admin) admin=await repo.save(repo.create({username,email,passwordHash:await this.hasher.hash(randomBytes(32).toString('hex')),role:PlatformAdminRole.SUPER_ADMIN,totpSecret:null,totpEnabled:false}));const token=randomBytes(32).toString('base64url');await this.redis.set('platform-admin-bootstrap:'+this.tokenHasher.hash(token),admin.id,'EX',86400);const appUrl=this.config.get<string>('PUBLIC_APP_URL')??'https://fpo-mis-app.onrender.com';await this.email.send({to:email,template:'INITIAL_ADMIN_SETUP_LINK',data:{setupLink:appUrl+'/?setupToken='+token}});return {sent:true};}
 async setPassword(token:string,password:string,confirmPassword:string){if(password!==confirmPassword)throw new ForbiddenException('Passwords do not match.');const id=await this.redis.get('platform-admin-bootstrap:'+this.tokenHasher.hash(token));if(!id)throw new NotFoundException('The setup link is invalid or expired.');const repo=this.dataSource.getRepository(PlatformAdminAccountEntity),admin=await repo.findOneBy({id});if(!admin)throw new NotFoundException('The setup link is invalid or expired.');admin.passwordHash=await this.hasher.hash(password);admin.totpSecret=this.totp.generateSecret();await repo.save(admin);return {totpUri:this.totp.keyUri(admin.totpSecret,admin.email,'Sanrakshit FPO MIS')};}
 async confirmMfa(token:string,code:string){const id=await this.redis.get('platform-admin-bootstrap:'+this.tokenHasher.hash(token));if(!id)throw new NotFoundException('The setup link is invalid or expired.');const repo=this.dataSource.getRepository(PlatformAdminAccountEntity),admin=await repo.findOneBy({id});if(!admin?.totpSecret||!(await this.totp.verify(code,admin.totpSecret)))throw new ForbiddenException('Authenticator code is invalid.');admin.totpEnabled=true;await repo.save(admin);await this.redis.del('platform-admin-bootstrap:'+this.tokenHasher.hash(token));return {ready:true};}
}