import { useEffect, useState } from 'react';
import { api, extractErrorMessage } from '../api/client';
import LoanDocuments, { type LoanDocumentData } from './LoanDocuments';

type Loan={id:string;loanApplicationNumber:string;fullName:string;mobile:string;requestedAmount:string;requestedTermMonths:number;status:string;sanctionLetterIssuedAt?:string|null;agreementExecutedAt?:string|null};
const today=()=>new Date().toISOString().slice(0,10);
const documentStage=(status:string)=>['SANCTIONED','AGREEMENT_EXECUTED','DISBURSED'].includes(status);

export default function LoanApplicationsAdmin(){
  const[rows,setRows]=useState<Loan[]>([]),[selected,setSelected]=useState<Loan|null>(null),[documents,setDocuments]=useState<LoanDocumentData|null>(null),[error,setError]=useState(''),[msg,setMsg]=useState('');
  const[field,setField]=useState({fieldVisitDate:today(),officer:'',observations:'',recommendation:'RECOMMEND'});
  const[sanction,setSanction]=useState({sanctionedAmount:'',termMonths:'',interestRate:'',processingFeeRate:'',repaymentFrequency:'MONTHLY',sanctionDate:today()});
  const[disbursement,setDisbursement]=useState({mode:'BANK_TRANSFER',reference:''});
  const load=async()=>{try{const next=(await api.get<Loan[]>('/loan-applications')).data;setRows(next);if(selected)setSelected(next.find(item=>item.id===selected.id)??null);return next}catch(e){setError(extractErrorMessage(e));return [] as Loan[]}};
  useEffect(()=>{void load()},[]);
  const choose=(loan:Loan)=>{setSelected(loan);setDocuments(null);setField({...field,fieldVisitDate:today()});setSanction({...sanction,sanctionedAmount:loan.requestedAmount,termMonths:String(loan.requestedTermMonths),sanctionDate:today()});setDisbursement({mode:'BANK_TRANSFER',reference:''})};
  const run=async(path:string,body?:unknown)=>{if(!selected)return;try{await api.post(`/loan-applications/${selected.id}/${path}`,body??{});setMsg('ऋण प्रक्रिया अपडेट हो गई।');setError('');await load()}catch(e){setError(extractErrorMessage(e));throw e}};
  const openDocuments=async(id:string)=>{try{setDocuments((await api.get<LoanDocumentData>(`/loan-applications/${id}/documents`)).data);setError('')}catch(e){setError(extractErrorMessage(e))}};
  const issueLetter=async()=>{await run('issue-sanction-letter');if(selected)await openDocuments(selected.id)};
  const executeAgreement=async()=>{await run('execute-agreement');if(selected)await openDocuments(selected.id)};
  return <div className="card"><h1>ऋण आवेदन और FPO कार्यप्रवाह</h1><p className="muted">आवेदन → समीक्षा → Field Visit → Sanction → Sanction Letter → Agreement → Disbursement</p>{error&&<div className="error">{error}</div>}{msg&&<div className="success">{msg}</div>}
    <div className="table-wrap"><table><thead><tr><th>आवेदन</th><th>कृषक</th><th>राशि/अवधि</th><th>स्थिति</th><th>कार्य</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.loanApplicationNumber}</td><td>{r.fullName}<br/><small>{r.mobile}</small></td><td>₹{r.requestedAmount} / {r.requestedTermMonths} माह</td><td><span className="badge">{r.status}</span></td><td><button onClick={()=>choose(r)}>खोलें</button></td></tr>)}</tbody></table></div>
    {selected&&<section className="card" style={{marginTop:16}}><h2>{selected.loanApplicationNumber} — {selected.fullName}</h2>
      {selected.status==='SUBMITTED'&&<button onClick={()=>void run('begin-review')}>समीक्षा शुरू करें</button>}
      {selected.status==='UNDER_REVIEW'&&<><h3>Field Visit विवरण</h3><div className="grid2"><label>भ्रमण तारीख<input type="date" value={field.fieldVisitDate} onChange={e=>setField({...field,fieldVisitDate:e.target.value})}/></label><label>FPO अधिकारी<input value={field.officer} onChange={e=>setField({...field,officer:e.target.value})}/></label></div><label>अवलोकन<textarea value={field.observations} onChange={e=>setField({...field,observations:e.target.value})}/></label><label>सिफारिश<select value={field.recommendation} onChange={e=>setField({...field,recommendation:e.target.value})}><option value="RECOMMEND">स्वीकृति की सिफारिश</option><option value="NOT_RECOMMEND">सिफारिश नहीं</option></select></label><button onClick={()=>void run('field-visit',field)}>Field Visit सुरक्षित करें</button></>}
      {selected.status==='FIELD_VISIT_COMPLETED'&&<><h3>Sanction विवरण</h3><div className="grid3"><label>स्वीकृत राशि<input type="number" value={sanction.sanctionedAmount} onChange={e=>setSanction({...sanction,sanctionedAmount:e.target.value})}/></label><label>अवधि (माह)<input type="number" value={sanction.termMonths} onChange={e=>setSanction({...sanction,termMonths:e.target.value})}/></label><label>ब्याज दर %<input type="number" value={sanction.interestRate} onChange={e=>setSanction({...sanction,interestRate:e.target.value})}/></label><label>Processing fee %<input type="number" value={sanction.processingFeeRate} onChange={e=>setSanction({...sanction,processingFeeRate:e.target.value})}/></label><label>किस्त<select value={sanction.repaymentFrequency} onChange={e=>setSanction({...sanction,repaymentFrequency:e.target.value})}><option>MONTHLY</option><option>QUARTERLY</option></select></label><label>Sanction तारीख<input type="date" value={sanction.sanctionDate} onChange={e=>setSanction({...sanction,sanctionDate:e.target.value})}/></label></div><button onClick={()=>void run('sanction',{...sanction,termMonths:Number(sanction.termMonths)})}>Sanction सुरक्षित करें</button></>}
      {documentStage(selected.status)&&<><button className="secondary" onClick={()=>void openDocuments(selected.id)}>Sanction Letter / Agreement / Checklist</button>{selected.status==='SANCTIONED'&&<p className="muted">पहले Sanction Letter जारी होने पर tick करें, फिर उसी स्क्रीन में signed Agreement दर्ज करें।</p>}</>}
      {selected.status==='AGREEMENT_EXECUTED'&&<><h3>Disbursement विवरण</h3><label>भुगतान तरीका<select value={disbursement.mode} onChange={e=>setDisbursement({...disbursement,mode:e.target.value})}><option value="BANK_TRANSFER">Bank transfer</option><option value="CASH">Cash</option><option value="CHEQUE">Cheque</option></select></label><label>लेन-देन/चेक संदर्भ<input value={disbursement.reference} onChange={e=>setDisbursement({...disbursement,reference:e.target.value})}/></label><button onClick={()=>void run('disburse',disbursement)}>Disbursement दर्ज करें</button></>}
      {selected.status==='DISBURSED'&&<p className="success">ऋण वितरण पूरा हो चुका है।</p>}
    </section>}
    {documents&&<LoanDocuments data={documents} onClose={()=>setDocuments(null)} onIssue={issueLetter} onAgreement={executeAgreement}/>}</div>
}
