import { useEffect, useState } from 'react';
import { api, extractErrorMessage } from '../api/client';

type Row = { id:string; applicationNumber:string; fullName:string; mobile:string; village:string; shareQuantity:number; shareAmount:string; status:string; memberNumber?:string; identityCardNumber?:string };
export default function MemberApplicationsAdmin() {
  const [rows,setRows]=useState<Row[]>([]); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [card,setCard]=useState<any>(null);
  const load=async()=>{ try { const r=await api.get<Row[]>('/member-applications'); setRows(r.data); } catch(e){setError(extractErrorMessage(e));} };
  useEffect(()=>{void load();},[]);
  const decide=async(id:string,status:'APPROVED'|'REJECTED')=>{ try { await api.post(`/member-applications/${id}/decision`,{status,note: status==='APPROVED'?'Shareholder application verified':'Application rejected'}); setMessage(`आवेदन ${status==='APPROVED'?'स्वीकृत':'अस्वीकृत'} हुआ।`); await load(); }catch(e){setError(extractErrorMessage(e));} };
  const showCard=async(id:string)=>{try {const r=await api.get(`/member-applications/${id}/identity-card`); setCard(r.data);}catch(e){setError(extractErrorMessage(e));}};
  return <div className="card"><h1>कृषक शेयरधारक आवेदन</h1><p className="muted">आवेदन जाँचें, स्वीकृत करें और पहचान‑पत्र जारी करें।</p>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}<div className="table-wrap"><table><thead><tr><th>आवेदन</th><th>कृषक</th><th>ग्राम</th><th>शेयर</th><th>स्थिति</th><th>कार्य</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.applicationNumber}</td><td>{r.fullName}<br/><small>{r.mobile}</small></td><td>{r.village}</td><td>{r.shareQuantity} / ₹{r.shareAmount}</td><td><span className="badge">{r.status}</span></td><td className="actions">{r.status==='PENDING'&&<><button onClick={()=>void decide(r.id,'APPROVED')}>स्वीकृत करें</button><button className="danger" onClick={()=>void decide(r.id,'REJECTED')}>अस्वीकृत</button></>}{r.status==='APPROVED'&&<button onClick={()=>void showCard(r.id)}>पहचान‑पत्र</button>}</td></tr>)}</tbody></table></div>{rows.length===0&&<p>अभी कोई आवेदन नहीं है।</p>}{card&&<section className="member-card"><div><strong>{card.fpoName}</strong><br/><small>कृषक शेयरधारक पहचान‑पत्र</small></div><hr/><h2>{card.member.fullName}</h2><p>Member No: <b>{card.member.memberNumber}</b></p><p>ID Card No: <b>{card.member.identityCardNumber}</b></p><p>FPO Code: {card.fpoCode} · Mobile: {card.member.mobile}</p><p>Village: {card.member.village}, {card.member.district}</p><button onClick={()=>window.print()}>प्रिंट / PDF में सहेजें</button><button className="secondary" onClick={()=>setCard(null)}>बंद करें</button></section>}</div>;
}