import { useState } from 'react';
import { api, extractErrorMessage } from '../api/client';

const initial = { fpoCode: 'SPCL', fullName: '', mobile: '', email: '', aadhaarLast4: '', pan: '', dateOfBirth: '', gender: 'MALE', address: '', village: '', district: 'Hamirpur', state: 'Uttar Pradesh', pincode: '210507', landHoldingAcres: '', shareQuantity: 1, shareAmount: '1000' };

export default function MemberApply() {
  const [form, setForm] = useState(initial); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState('');
  const set = (key: keyof typeof initial, value: string | number) => setForm({ ...form, [key]: value });
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(''); setSuccess(''); try { const r = await api.post('/member-applications', { ...form, fpoCode: form.fpoCode.toUpperCase(), shareQuantity: Number(form.shareQuantity), ...(form.email ? {} : { email: undefined }), ...(form.aadhaarLast4 ? {} : { aadhaarLast4: undefined }), ...(form.pan ? {} : { pan: undefined }), ...(form.dateOfBirth ? {} : { dateOfBirth: undefined }), ...(form.landHoldingAcres ? {} : { landHoldingAcres: undefined }) }); setSuccess(`आवेदन सफलतापूर्वक जमा हुआ। आवेदन संख्या: ${r.data.applicationNumber}`); setForm({ ...initial, fpoCode: form.fpoCode }); } catch (e) { setError(extractErrorMessage(e)); } finally { setBusy(false); } }
  return <div className="card"><h1>कृषक शेयरधारक आवेदन</h1><p className="muted">Sanrakshit Producer Company Limited में सदस्यता एवं शेयर आवेदन</p>{success && <div className="success">{success}<br/>FPO द्वारा जाँच एवं स्वीकृति के बाद पहचान‑पत्र जारी होगा।</div>}{error && <div className="error">{error}</div>}<form onSubmit={submit}><div className="grid2"><label>FPO Code<input required value={form.fpoCode} onChange={e=>set('fpoCode', e.target.value)}/></label><label>पूरा नाम<input required value={form.fullName} onChange={e=>set('fullName', e.target.value)}/></label><label>मोबाइल नम्बर<input required maxLength={10} value={form.mobile} onChange={e=>set('mobile', e.target.value)}/></label><label>ईमेल (वैकल्पिक)<input type="email" value={form.email} onChange={e=>set('email', e.target.value)}/></label><label>आधार के अन्तिम 4 अंक<input maxLength={4} inputMode="numeric" value={form.aadhaarLast4} onChange={e=>set('aadhaarLast4', e.target.value)}/></label><label>PAN (वैकल्पिक)<input value={form.pan} onChange={e=>set('pan', e.target.value.toUpperCase())}/></label><label>जन्म तिथि<input type="date" value={form.dateOfBirth} onChange={e=>set('dateOfBirth', e.target.value)}/></label><label>लिंग<select value={form.gender} onChange={e=>set('gender', e.target.value)}><option value="MALE">पुरुष</option><option value="FEMALE">महिला</option><option value="OTHER">अन्य</option></select></label><label>पूरा पता<input required value={form.address} onChange={e=>set('address', e.target.value)}/></label><label>ग्राम<input required value={form.village} onChange={e=>set('village', e.target.value)}/></label><label>जिला<input required value={form.district} onChange={e=>set('district', e.target.value)}/></label><label>राज्य<input required value={form.state} onChange={e=>set('state', e.target.value)}/></label><label>पिनकोड<input required maxLength={6} value={form.pincode} onChange={e=>set('pincode', e.target.value)}/></label><label>भूमि (एकड़, वैकल्पिक)<input inputMode="decimal" value={form.landHoldingAcres} onChange={e=>set('landHoldingAcres', e.target.value)}/></label><label>शेयरों की संख्या<input required min={1} type="number" value={form.shareQuantity} onChange={e=>set('shareQuantity', Number(e.target.value))}/></label><label>कुल शेयर राशि (₹)<input required inputMode="decimal" value={form.shareAmount} onChange={e=>set('shareAmount', e.target.value)}/></label></div><p className="muted">सुरक्षा हेतु पूरा आधार नंबर न भरें—केवल अंतिम 4 अंक भरें।</p><button disabled={busy}>{busy ? 'जमा हो रहा है…' : 'शेयरधारक आवेदन जमा करें'}</button></form></div>;
}